# Generated by Django 6.0.5 on 2026-05-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'TaskType', 'verbose_name_plural': 'TaskTypes'},
        ),
    ]
